# Generated by Django 3.1 on 2020-09-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('budget', models.IntegerField(default=80000000)),
                ('rating', models.IntegerField(default=75)),
                ('league', models.CharField(max_length=20, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('api_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=3)),
                ('price', models.IntegerField(default=20000000)),
                ('contract_length', models.IntegerField(default=36)),
                ('rating', models.IntegerField(default=70)),
                ('country', models.CharField(default='Unknown', max_length=20)),
                ('on_loan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='football_manager.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Archived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('approved', models.BooleanField()),
                ('player_first_name', models.CharField(max_length=255)),
                ('player_last_name', models.CharField(max_length=255)),
                ('transaction', models.CharField(choices=[('Loan', 'Loan'), ('Sell', 'Sell')], default='Sell', max_length=20)),
                ('buyer_club_name', models.CharField(max_length=255, null=True)),
                ('seller_club_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('transaction', models.CharField(choices=[('Loan', 'Loan'), ('Sell', 'Sell')], default='Sell', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_transfers', to='football_manager.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='football_manager.player')),
                ('seller_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_transfers', to='football_manager.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club', to='football_manager.user'),
        ),
    ]
